### ISSUE TITLE
Typo in your PDF copy of Chapter 9?

### ISSUE THREAD

**Issue by mangozy** [deep-learning-with-pytorch/dlwpt-code#11]
Is this a typo in your PDF copy of Chapter 9?

In your Chapter 9 it says: `If you want to jump ahead, you can use the code/p2ch09_explore_data.ipynb Jupyter Notebook to get started`. But I can't find the code/p2ch09 folder in your Github repository.

![typo](https://user-images.githubusercontent.com/32133971/88470581-0aea5100-cecc-11ea-96a3-2483c8113095.png)

![typo](https://user-images.githubusercontent.com/32133971/88470617-86e49900-cecc-11ea-9287-7808f3311869.png)

**Comment by elistevens** [comment]
I could have sworn I'd already answered this, but now I can't find any evidence that I actually have. Sorry! If I did send you an answer already... Could you please reply back to me on the thread?

In any case, the `code/` is due to us having a private git repo that has the manuscript, images, code, etc. and what's here on github is an export of that code directory. Early on, chapters 9 and 10 were one (huge) chapter, but we ended up splitting it, and somehow this text has survived since then with nobody noticing it needed to be updated. The file it's talking about is `p2ch10_explore_data.ipynb`.

I'll drop an update in the ERRATA.html that will be landing in the repo shortly.

Thanks for the report!
