### ISSUE TITLE
A mistake in section 10.5.4 "Rendering the data" of the book

### ISSUE THREAD

**Issue by jh-foo** [deep-learning-with-pytorch/dlwpt-code#23]
\# In[7]:
%matplotlib inline
from p2ch10.vis import findNoduleSamples, showNodule
noduleSample_list = findNoduleSamples()
error: cannot import name 'findPositiveSampls' from 'chapter10.vis'
__________________________________________________________

Because the p2ch10.vis does not contain findNoduleSamples and showNodule.
correction:
\# In[7]:
%matplotlib inline
from p2ch10.vis import findPositiveSamples, showCandidate
positiveSample_list = findPositiveSamples()

**Comment by elistevens** [comment]
This one has me stumped, since I see the same change you suggest in my source files for the book, committed back in January 2020. I'm not sure how the old code didn't get updated when the book went to print six months later.

Thank you for reporting this; I'll update the errata and let the publisher know.
